:- dynamic(heuri/3).

heuri(ahmedabad,agartala,2).
heuri(bangalore,agartala,3).
heuri(bhubaneshwar,agartala,4).
heuri(bombay,agartala,5).
heuri(calcutta,agartala,6).
heuri(chandigarh,agartala,7).
heuri(cochin,agartala,8).
heuri(delhi,agartala,9).
heuri(hyderabad,agartala,10).
heuri(indore,agartala,11).
heuri(jaipur,agartala,12).
heuri(kanpur,agartala,13).
heuri(lucknow,agartala,14).
heuri(madras,agartala,15).
heuri(nagpur,agartala,16).
heuri(nasik,agartala,17).
heuri(panjim,agartala,18).
heuri(patna,agartala,19).
heuri(pondicherry,agartala,20).
heuri(pune,agartala,21).
heuri(ahmedabad,agra,3).
heuri(bangalore,agra,4).
heuri(bhubaneshwar,agra,5).
heuri(bombay,agra,6).
heuri(calcutta,agra,7).
heuri(chandigarh,agra,8).
heuri(cochin,agra,9).
heuri(delhi,agra,10).
heuri(hyderabad,agra,11).
heuri(indore,agra,12).
heuri(jaipur,agra,13).
heuri(kanpur,agra,14).
heuri(lucknow,agra,15).
heuri(madras,agra,16).
heuri(nagpur,agra,17).
heuri(nasik,agra,18).
heuri(panjim,agra,19).
heuri(patna,agra,20).
heuri(pondicherry,agra,21).
heuri(pune,agra,22).
heuri(ahmedabad,ahmedabad,0).
heuri(bangalore,ahmedabad,5).
heuri(bhubaneshwar,ahmedabad,6).
heuri(bombay,ahmedabad,7).
heuri(calcutta,ahmedabad,8).
heuri(chandigarh,ahmedabad,9).
heuri(cochin,ahmedabad,10).
heuri(delhi,ahmedabad,11).
heuri(hyderabad,ahmedabad,12).
heuri(indore,ahmedabad,13).
heuri(jaipur,ahmedabad,14).
heuri(kanpur,ahmedabad,15).
heuri(lucknow,ahmedabad,16).
heuri(madras,ahmedabad,17).
heuri(nagpur,ahmedabad,18).
heuri(nasik,ahmedabad,19).
heuri(panjim,ahmedabad,20).
heuri(patna,ahmedabad,21).
heuri(pondicherry,ahmedabad,22).
heuri(pune,ahmedabad,23).
heuri(ahmedabad,allahabad,5).
heuri(bangalore,allahabad,6).
heuri(bhubaneshwar,allahabad,7).
heuri(bombay,allahabad,8).
heuri(calcutta,allahabad,9).
heuri(chandigarh,allahabad,10).
heuri(cochin,allahabad,11).
heuri(delhi,allahabad,12).
heuri(hyderabad,allahabad,13).
heuri(indore,allahabad,14).
heuri(jaipur,allahabad,15).
heuri(kanpur,allahabad,16).
heuri(lucknow,allahabad,17).
heuri(madras,allahabad,18).
heuri(nagpur,allahabad,19).
heuri(nasik,allahabad,20).
heuri(panjim,allahabad,21).
heuri(patna,allahabad,22).
heuri(pondicherry,allahabad,23).
heuri(pune,allahabad,24).
heuri(ahmedabad,amritsar,6).
heuri(bangalore,amritsar,7).
heuri(bhubaneshwar,amritsar,8).
heuri(bombay,amritsar,9).
heuri(calcutta,amritsar,10).
heuri(chandigarh,amritsar,11).
heuri(cochin,amritsar,12).
heuri(delhi,amritsar,13).
heuri(hyderabad,amritsar,14).
heuri(indore,amritsar,15).
heuri(jaipur,amritsar,16).
heuri(kanpur,amritsar,17).
heuri(lucknow,amritsar,18).
heuri(madras,amritsar,19).
heuri(nagpur,amritsar,20).
heuri(nasik,amritsar,21).
heuri(panjim,amritsar,22).
heuri(patna,amritsar,23).
heuri(pondicherry,amritsar,24).
heuri(pune,amritsar,25).
heuri(ahmedabad,asansol,7).
heuri(bangalore,asansol,8).
heuri(bhubaneshwar,asansol,9).
heuri(bombay,asansol,10).
heuri(calcutta,asansol,11).
heuri(chandigarh,asansol,12).
heuri(cochin,asansol,13).
heuri(delhi,asansol,14).
heuri(hyderabad,asansol,15).
heuri(indore,asansol,16).
heuri(jaipur,asansol,17).
heuri(kanpur,asansol,18).
heuri(lucknow,asansol,19).
heuri(madras,asansol,20).
heuri(nagpur,asansol,21).
heuri(nasik,asansol,22).
heuri(panjim,asansol,23).
heuri(patna,asansol,24).
heuri(pondicherry,asansol,25).
heuri(pune,asansol,26).
heuri(ahmedabad,bangalore,8).
heuri(bangalore,bangalore,0).
heuri(bhubaneshwar,bangalore,10).
heuri(bombay,bangalore,11).
heuri(calcutta,bangalore,12).
heuri(chandigarh,bangalore,13).
heuri(cochin,bangalore,14).
heuri(delhi,bangalore,15).
heuri(hyderabad,bangalore,16).
heuri(indore,bangalore,17).
heuri(jaipur,bangalore,18).
heuri(kanpur,bangalore,19).
heuri(lucknow,bangalore,20).
heuri(madras,bangalore,21).
heuri(nagpur,bangalore,22).
heuri(nasik,bangalore,23).
heuri(panjim,bangalore,24).
heuri(patna,bangalore,25).
heuri(pondicherry,bangalore,26).
heuri(pune,bangalore,27).
heuri(ahmedabad,baroda,9).
heuri(bangalore,baroda,10).
heuri(bhubaneshwar,baroda,11).
heuri(bombay,baroda,12).
heuri(calcutta,baroda,13).
heuri(chandigarh,baroda,14).
heuri(cochin,baroda,15).
heuri(delhi,baroda,16).
heuri(hyderabad,baroda,17).
heuri(indore,baroda,18).
heuri(jaipur,baroda,19).
heuri(kanpur,baroda,20).
heuri(lucknow,baroda,21).
heuri(madras,baroda,22).
heuri(nagpur,baroda,23).
heuri(nasik,baroda,24).
heuri(panjim,baroda,25).
heuri(patna,baroda,26).
heuri(pondicherry,baroda,27).
heuri(pune,baroda,28).
heuri(ahmedabad,bhopal,10).
heuri(bangalore,bhopal,11).
heuri(bhubaneshwar,bhopal,12).
heuri(bombay,bhopal,13).
heuri(calcutta,bhopal,14).
heuri(chandigarh,bhopal,15).
heuri(cochin,bhopal,16).
heuri(delhi,bhopal,17).
heuri(hyderabad,bhopal,18).
heuri(indore,bhopal,19).
heuri(jaipur,bhopal,20).
heuri(kanpur,bhopal,21).
heuri(lucknow,bhopal,22).
heuri(madras,bhopal,23).
heuri(nagpur,bhopal,24).
heuri(nasik,bhopal,25).
heuri(panjim,bhopal,26).
heuri(patna,bhopal,27).
heuri(pondicherry,bhopal,28).
heuri(pune,bhopal,29).
heuri(ahmedabad,bhubaneshwar,11).
heuri(bangalore,bhubaneshwar,12).
heuri(bhubaneshwar,bhubaneshwar,0).
heuri(bombay,bhubaneshwar,14).
heuri(calcutta,bhubaneshwar,15).
heuri(chandigarh,bhubaneshwar,16).
heuri(cochin,bhubaneshwar,17).
heuri(delhi,bhubaneshwar,18).
heuri(hyderabad,bhubaneshwar,19).
heuri(indore,bhubaneshwar,20).
heuri(jaipur,bhubaneshwar,21).
heuri(kanpur,bhubaneshwar,22).
heuri(lucknow,bhubaneshwar,23).
heuri(madras,bhubaneshwar,24).
heuri(nagpur,bhubaneshwar,25).
heuri(nasik,bhubaneshwar,26).
heuri(panjim,bhubaneshwar,27).
heuri(patna,bhubaneshwar,28).
heuri(pondicherry,bhubaneshwar,29).
heuri(pune,bhubaneshwar,30).
heuri(ahmedabad,bombay,12).
heuri(bangalore,bombay,13).
heuri(bhubaneshwar,bombay,14).
heuri(bombay,bombay,0).
heuri(calcutta,bombay,16).
heuri(chandigarh,bombay,17).
heuri(cochin,bombay,18).
heuri(delhi,bombay,19).
heuri(hyderabad,bombay,20).
heuri(indore,bombay,21).
heuri(jaipur,bombay,22).
heuri(kanpur,bombay,23).
heuri(lucknow,bombay,24).
heuri(madras,bombay,25).
heuri(nagpur,bombay,26).
heuri(nasik,bombay,27).
heuri(panjim,bombay,28).
heuri(patna,bombay,29).
heuri(pondicherry,bombay,30).
heuri(pune,bombay,31).
heuri(ahmedabad,calcutta,13).
heuri(bangalore,calcutta,14).
heuri(bhubaneshwar,calcutta,15).
heuri(bombay,calcutta,16).
heuri(calcutta,calcutta,0).
heuri(chandigarh,calcutta,18).
heuri(cochin,calcutta,19).
heuri(delhi,calcutta,20).
heuri(hyderabad,calcutta,21).
heuri(indore,calcutta,22).
heuri(jaipur,calcutta,23).
heuri(kanpur,calcutta,24).
heuri(lucknow,calcutta,25).
heuri(madras,calcutta,26).
heuri(nagpur,calcutta,27).
heuri(nasik,calcutta,28).
heuri(panjim,calcutta,29).
heuri(patna,calcutta,30).
heuri(pondicherry,calcutta,31).
heuri(pune,calcutta,32).
heuri(ahmedabad,calicut,14).
heuri(bangalore,calicut,15).
heuri(bhubaneshwar,calicut,16).
heuri(bombay,calicut,17).
heuri(calcutta,calicut,18).
heuri(chandigarh,calicut,19).
heuri(cochin,calicut,20).
heuri(delhi,calicut,21).
heuri(hyderabad,calicut,22).
heuri(indore,calicut,23).
heuri(jaipur,calicut,24).
heuri(kanpur,calicut,25).
heuri(lucknow,calicut,26).
heuri(madras,calicut,27).
heuri(nagpur,calicut,28).
heuri(nasik,calicut,29).
heuri(panjim,calicut,30).
heuri(patna,calicut,31).
heuri(pondicherry,calicut,32).
heuri(pune,calicut,33).
heuri(ahmedabad,chandigarh,15).
heuri(bangalore,chandigarh,16).
heuri(bhubaneshwar,chandigarh,17).
heuri(bombay,chandigarh,18).
heuri(calcutta,chandigarh,19).
heuri(chandigarh,chandigarh,0).
heuri(cochin,chandigarh,21).
heuri(delhi,chandigarh,22).
heuri(hyderabad,chandigarh,23).
heuri(indore,chandigarh,24).
heuri(jaipur,chandigarh,25).
heuri(kanpur,chandigarh,26).
heuri(lucknow,chandigarh,27).
heuri(madras,chandigarh,28).
heuri(nagpur,chandigarh,29).
heuri(nasik,chandigarh,30).
heuri(panjim,chandigarh,31).
heuri(patna,chandigarh,32).
heuri(pondicherry,chandigarh,33).
heuri(pune,chandigarh,34).
heuri(ahmedabad,cochin,16).
heuri(bangalore,cochin,17).
heuri(bhubaneshwar,cochin,18).
heuri(bombay,cochin,19).
heuri(calcutta,cochin,20).
heuri(chandigarh,cochin,21).
heuri(cochin,cochin,0).
heuri(delhi,cochin,23).
heuri(hyderabad,cochin,24).
heuri(indore,cochin,25).
heuri(jaipur,cochin,26).
heuri(kanpur,cochin,27).
heuri(lucknow,cochin,28).
heuri(madras,cochin,29).
heuri(nagpur,cochin,30).
heuri(nasik,cochin,31).
heuri(panjim,cochin,32).
heuri(patna,cochin,33).
heuri(pondicherry,cochin,34).
heuri(pune,cochin,35).
heuri(ahmedabad,coimbatore,17).
heuri(bangalore,coimbatore,18).
heuri(bhubaneshwar,coimbatore,19).
heuri(bombay,coimbatore,20).
heuri(calcutta,coimbatore,21).
heuri(chandigarh,coimbatore,22).
heuri(cochin,coimbatore,23).
heuri(delhi,coimbatore,24).
heuri(hyderabad,coimbatore,25).
heuri(indore,coimbatore,26).
heuri(jaipur,coimbatore,27).
heuri(kanpur,coimbatore,28).
heuri(lucknow,coimbatore,29).
heuri(madras,coimbatore,30).
heuri(nagpur,coimbatore,31).
heuri(nasik,coimbatore,32).
heuri(panjim,coimbatore,33).
heuri(patna,coimbatore,34).
heuri(pondicherry,coimbatore,35).
heuri(pune,coimbatore,36).
heuri(ahmedabad,delhi,18).
heuri(bangalore,delhi,19).
heuri(bhubaneshwar,delhi,20).
heuri(bombay,delhi,21).
heuri(calcutta,delhi,22).
heuri(chandigarh,delhi,23).
heuri(cochin,delhi,24).
heuri(delhi,delhi,0).
heuri(hyderabad,delhi,26).
heuri(indore,delhi,27).
heuri(jaipur,delhi,28).
heuri(kanpur,delhi,29).
heuri(lucknow,delhi,30).
heuri(madras,delhi,31).
heuri(nagpur,delhi,32).
heuri(nasik,delhi,33).
heuri(panjim,delhi,34).
heuri(patna,delhi,35).
heuri(pondicherry,delhi,36).
heuri(pune,delhi,37).
heuri(ahmedabad,gwalior,19).
heuri(bangalore,gwalior,20).
heuri(bhubaneshwar,gwalior,21).
heuri(bombay,gwalior,22).
heuri(calcutta,gwalior,23).
heuri(chandigarh,gwalior,24).
heuri(cochin,gwalior,25).
heuri(delhi,gwalior,26).
heuri(hyderabad,gwalior,27).
heuri(indore,gwalior,28).
heuri(jaipur,gwalior,29).
heuri(kanpur,gwalior,30).
heuri(lucknow,gwalior,31).
heuri(madras,gwalior,32).
heuri(nagpur,gwalior,33).
heuri(nasik,gwalior,34).
heuri(panjim,gwalior,35).
heuri(patna,gwalior,36).
heuri(pondicherry,gwalior,37).
heuri(pune,gwalior,38).
heuri(ahmedabad,hubli,20).
heuri(bangalore,hubli,21).
heuri(bhubaneshwar,hubli,22).
heuri(bombay,hubli,23).
heuri(calcutta,hubli,24).
heuri(chandigarh,hubli,25).
heuri(cochin,hubli,26).
heuri(delhi,hubli,27).
heuri(hyderabad,hubli,28).
heuri(indore,hubli,29).
heuri(jaipur,hubli,30).
heuri(kanpur,hubli,31).
heuri(lucknow,hubli,32).
heuri(madras,hubli,33).
heuri(nagpur,hubli,34).
heuri(nasik,hubli,35).
heuri(panjim,hubli,36).
heuri(patna,hubli,37).
heuri(pondicherry,hubli,38).
heuri(pune,hubli,39).
heuri(ahmedabad,hyderabad,21).
heuri(bangalore,hyderabad,22).
heuri(bhubaneshwar,hyderabad,23).
heuri(bombay,hyderabad,24).
heuri(calcutta,hyderabad,25).
heuri(chandigarh,hyderabad,26).
heuri(cochin,hyderabad,27).
heuri(delhi,hyderabad,28).
heuri(hyderabad,hyderabad,0).
heuri(indore,hyderabad,30).
heuri(jaipur,hyderabad,31).
heuri(kanpur,hyderabad,32).
heuri(lucknow,hyderabad,33).
heuri(madras,hyderabad,34).
heuri(nagpur,hyderabad,35).
heuri(nasik,hyderabad,36).
heuri(panjim,hyderabad,37).
heuri(patna,hyderabad,38).
heuri(pondicherry,hyderabad,39).
heuri(pune,hyderabad,40).
heuri(ahmedabad,imphal,22).
heuri(bangalore,imphal,23).
heuri(bhubaneshwar,imphal,24).
heuri(bombay,imphal,25).
heuri(calcutta,imphal,26).
heuri(chandigarh,imphal,27).
heuri(cochin,imphal,28).
heuri(delhi,imphal,29).
heuri(hyderabad,imphal,30).
heuri(indore,imphal,31).
heuri(jaipur,imphal,32).
heuri(kanpur,imphal,33).
heuri(lucknow,imphal,34).
heuri(madras,imphal,35).
heuri(nagpur,imphal,36).
heuri(nasik,imphal,37).
heuri(panjim,imphal,38).
heuri(patna,imphal,39).
heuri(pondicherry,imphal,40).
heuri(pune,imphal,41).
heuri(ahmedabad,indore,23).
heuri(bangalore,indore,24).
heuri(bhubaneshwar,indore,25).
heuri(bombay,indore,26).
heuri(calcutta,indore,27).
heuri(chandigarh,indore,28).
heuri(cochin,indore,29).
heuri(delhi,indore,30).
heuri(hyderabad,indore,31).
heuri(indore,indore,0).
heuri(jaipur,indore,33).
heuri(kanpur,indore,34).
heuri(lucknow,indore,35).
heuri(madras,indore,36).
heuri(nagpur,indore,37).
heuri(nasik,indore,38).
heuri(panjim,indore,39).
heuri(patna,indore,40).
heuri(pondicherry,indore,41).
heuri(pune,indore,42).
heuri(ahmedabad,jabalpur,24).
heuri(bangalore,jabalpur,25).
heuri(bhubaneshwar,jabalpur,26).
heuri(bombay,jabalpur,27).
heuri(calcutta,jabalpur,28).
heuri(chandigarh,jabalpur,29).
heuri(cochin,jabalpur,30).
heuri(delhi,jabalpur,31).
heuri(hyderabad,jabalpur,32).
heuri(indore,jabalpur,33).
heuri(jaipur,jabalpur,34).
heuri(kanpur,jabalpur,35).
heuri(lucknow,jabalpur,36).
heuri(madras,jabalpur,37).
heuri(nagpur,jabalpur,38).
heuri(nasik,jabalpur,39).
heuri(panjim,jabalpur,40).
heuri(patna,jabalpur,41).
heuri(pondicherry,jabalpur,42).
heuri(pune,jabalpur,43).
heuri(ahmedabad,jaipur,25).
heuri(bangalore,jaipur,26).
heuri(bhubaneshwar,jaipur,27).
heuri(bombay,jaipur,28).
heuri(calcutta,jaipur,29).
heuri(chandigarh,jaipur,30).
heuri(cochin,jaipur,31).
heuri(delhi,jaipur,32).
heuri(hyderabad,jaipur,33).
heuri(indore,jaipur,34).
heuri(jaipur,jaipur,0).
heuri(kanpur,jaipur,36).
heuri(lucknow,jaipur,37).
heuri(madras,jaipur,38).
heuri(nagpur,jaipur,39).
heuri(nasik,jaipur,40).
heuri(panjim,jaipur,41).
heuri(patna,jaipur,42).
heuri(pondicherry,jaipur,43).
heuri(pune,jaipur,44).
heuri(ahmedabad,jamshedpur,26).
heuri(bangalore,jamshedpur,27).
heuri(bhubaneshwar,jamshedpur,28).
heuri(bombay,jamshedpur,29).
heuri(calcutta,jamshedpur,30).
heuri(chandigarh,jamshedpur,31).
heuri(cochin,jamshedpur,32).
heuri(delhi,jamshedpur,33).
heuri(hyderabad,jamshedpur,34).
heuri(indore,jamshedpur,35).
heuri(jaipur,jamshedpur,36).
heuri(kanpur,jamshedpur,37).
heuri(lucknow,jamshedpur,38).
heuri(madras,jamshedpur,39).
heuri(nagpur,jamshedpur,40).
heuri(nasik,jamshedpur,41).
heuri(panjim,jamshedpur,42).
heuri(patna,jamshedpur,43).
heuri(pondicherry,jamshedpur,44).
heuri(pune,jamshedpur,45).
heuri(ahmedabad,jullundur,27).
heuri(bangalore,jullundur,28).
heuri(bhubaneshwar,jullundur,29).
heuri(bombay,jullundur,30).
heuri(calcutta,jullundur,31).
heuri(chandigarh,jullundur,32).
heuri(cochin,jullundur,33).
heuri(delhi,jullundur,34).
heuri(hyderabad,jullundur,35).
heuri(indore,jullundur,36).
heuri(jaipur,jullundur,37).
heuri(kanpur,jullundur,38).
heuri(lucknow,jullundur,39).
heuri(madras,jullundur,40).
heuri(nagpur,jullundur,41).
heuri(nasik,jullundur,42).
heuri(panjim,jullundur,43).
heuri(patna,jullundur,44).
heuri(pondicherry,jullundur,45).
heuri(pune,jullundur,46).
heuri(ahmedabad,kanpur,28).
heuri(bangalore,kanpur,29).
heuri(bhubaneshwar,kanpur,30).
heuri(bombay,kanpur,31).
heuri(calcutta,kanpur,32).
heuri(chandigarh,kanpur,33).
heuri(cochin,kanpur,34).
heuri(delhi,kanpur,35).
heuri(hyderabad,kanpur,36).
heuri(indore,kanpur,37).
heuri(jaipur,kanpur,38).
heuri(kanpur,kanpur,0).
heuri(lucknow,kanpur,40).
heuri(madras,kanpur,41).
heuri(nagpur,kanpur,42).
heuri(nasik,kanpur,43).
heuri(panjim,kanpur,44).
heuri(patna,kanpur,45).
heuri(pondicherry,kanpur,46).
heuri(pune,kanpur,47).
heuri(ahmedabad,kolhapur,29).
heuri(bangalore,kolhapur,30).
heuri(bhubaneshwar,kolhapur,31).
heuri(bombay,kolhapur,32).
heuri(calcutta,kolhapur,33).
heuri(chandigarh,kolhapur,34).
heuri(cochin,kolhapur,35).
heuri(delhi,kolhapur,36).
heuri(hyderabad,kolhapur,37).
heuri(indore,kolhapur,38).
heuri(jaipur,kolhapur,39).
heuri(kanpur,kolhapur,40).
heuri(lucknow,kolhapur,41).
heuri(madras,kolhapur,42).
heuri(nagpur,kolhapur,43).
heuri(nasik,kolhapur,44).
heuri(panjim,kolhapur,45).
heuri(patna,kolhapur,46).
heuri(pondicherry,kolhapur,47).
heuri(pune,kolhapur,48).
heuri(ahmedabad,lucknow,30).
heuri(bangalore,lucknow,31).
heuri(bhubaneshwar,lucknow,32).
heuri(bombay,lucknow,33).
heuri(calcutta,lucknow,34).
heuri(chandigarh,lucknow,35).
heuri(cochin,lucknow,36).
heuri(delhi,lucknow,37).
heuri(hyderabad,lucknow,38).
heuri(indore,lucknow,39).
heuri(jaipur,lucknow,40).
heuri(kanpur,lucknow,41).
heuri(lucknow,lucknow,0).
heuri(madras,lucknow,43).
heuri(nagpur,lucknow,44).
heuri(nasik,lucknow,45).
heuri(panjim,lucknow,46).
heuri(patna,lucknow,47).
heuri(pondicherry,lucknow,48).
heuri(pune,lucknow,49).
heuri(ahmedabad,ludhiana,31).
heuri(bangalore,ludhiana,32).
heuri(bhubaneshwar,ludhiana,33).
heuri(bombay,ludhiana,34).
heuri(calcutta,ludhiana,35).
heuri(chandigarh,ludhiana,36).
heuri(cochin,ludhiana,37).
heuri(delhi,ludhiana,38).
heuri(hyderabad,ludhiana,39).
heuri(indore,ludhiana,40).
heuri(jaipur,ludhiana,41).
heuri(kanpur,ludhiana,42).
heuri(lucknow,ludhiana,43).
heuri(madras,ludhiana,44).
heuri(nagpur,ludhiana,45).
heuri(nasik,ludhiana,46).
heuri(panjim,ludhiana,47).
heuri(patna,ludhiana,48).
heuri(pondicherry,ludhiana,49).
heuri(pune,ludhiana,50).
heuri(ahmedabad,madras,32).
heuri(bangalore,madras,33).
heuri(bhubaneshwar,madras,34).
heuri(bombay,madras,35).
heuri(calcutta,madras,36).
heuri(chandigarh,madras,37).
heuri(cochin,madras,38).
heuri(delhi,madras,39).
heuri(hyderabad,madras,40).
heuri(indore,madras,41).
heuri(jaipur,madras,42).
heuri(kanpur,madras,43).
heuri(lucknow,madras,44).
heuri(madras,madras,0).
heuri(nagpur,madras,46).
heuri(nasik,madras,47).
heuri(panjim,madras,48).
heuri(patna,madras,49).
heuri(pondicherry,madras,50).
heuri(pune,madras,51).
heuri(ahmedabad,madurai,33).
heuri(bangalore,madurai,34).
heuri(bhubaneshwar,madurai,35).
heuri(bombay,madurai,36).
heuri(calcutta,madurai,37).
heuri(chandigarh,madurai,38).
heuri(cochin,madurai,39).
heuri(delhi,madurai,40).
heuri(hyderabad,madurai,41).
heuri(indore,madurai,42).
heuri(jaipur,madurai,43).
heuri(kanpur,madurai,44).
heuri(lucknow,madurai,45).
heuri(madras,madurai,46).
heuri(nagpur,madurai,47).
heuri(nasik,madurai,48).
heuri(panjim,madurai,49).
heuri(patna,madurai,50).
heuri(pondicherry,madurai,51).
heuri(pune,madurai,52).
heuri(ahmedabad,meerut,34).
heuri(bangalore,meerut,35).
heuri(bhubaneshwar,meerut,36).
heuri(bombay,meerut,37).
heuri(calcutta,meerut,38).
heuri(chandigarh,meerut,39).
heuri(cochin,meerut,40).
heuri(delhi,meerut,41).
heuri(hyderabad,meerut,42).
heuri(indore,meerut,43).
heuri(jaipur,meerut,44).
heuri(kanpur,meerut,45).
heuri(lucknow,meerut,46).
heuri(madras,meerut,47).
heuri(nagpur,meerut,48).
heuri(nasik,meerut,49).
heuri(panjim,meerut,50).
heuri(patna,meerut,51).
heuri(pondicherry,meerut,52).
heuri(pune,meerut,53).
heuri(ahmedabad,nagpur,35).
heuri(bangalore,nagpur,36).
heuri(bhubaneshwar,nagpur,37).
heuri(bombay,nagpur,38).
heuri(calcutta,nagpur,39).
heuri(chandigarh,nagpur,40).
heuri(cochin,nagpur,41).
heuri(delhi,nagpur,42).
heuri(hyderabad,nagpur,43).
heuri(indore,nagpur,44).
heuri(jaipur,nagpur,45).
heuri(kanpur,nagpur,46).
heuri(lucknow,nagpur,47).
heuri(madras,nagpur,48).
heuri(nagpur,nagpur,0).
heuri(nasik,nagpur,50).
heuri(panjim,nagpur,51).
heuri(patna,nagpur,52).
heuri(pondicherry,nagpur,53).
heuri(pune,nagpur,54).
heuri(ahmedabad,nasik,36).
heuri(bangalore,nasik,37).
heuri(bhubaneshwar,nasik,38).
heuri(bombay,nasik,39).
heuri(calcutta,nasik,40).
heuri(chandigarh,nasik,41).
heuri(cochin,nasik,42).
heuri(delhi,nasik,43).
heuri(hyderabad,nasik,44).
heuri(indore,nasik,45).
heuri(jaipur,nasik,46).
heuri(kanpur,nasik,47).
heuri(lucknow,nasik,48).
heuri(madras,nasik,49).
heuri(nagpur,nasik,50).
heuri(nasik,nasik,0).
heuri(panjim,nasik,52).
heuri(patna,nasik,53).
heuri(pondicherry,nasik,54).
heuri(pune,nasik,55).
heuri(ahmedabad,panjim,37).
heuri(bangalore,panjim,38).
heuri(bhubaneshwar,panjim,39).
heuri(bombay,panjim,40).
heuri(calcutta,panjim,41).
heuri(chandigarh,panjim,42).
heuri(cochin,panjim,43).
heuri(delhi,panjim,44).
heuri(hyderabad,panjim,45).
heuri(indore,panjim,46).
heuri(jaipur,panjim,47).
heuri(kanpur,panjim,48).
heuri(lucknow,panjim,49).
heuri(madras,panjim,50).
heuri(nagpur,panjim,51).
heuri(nasik,panjim,52).
heuri(panjim,panjim,0).
heuri(patna,panjim,54).
heuri(pondicherry,panjim,55).
heuri(pune,panjim,56).
heuri(ahmedabad,patna,38).
heuri(bangalore,patna,39).
heuri(bhubaneshwar,patna,40).
heuri(bombay,patna,41).
heuri(calcutta,patna,42).
heuri(chandigarh,patna,43).
heuri(cochin,patna,44).
heuri(delhi,patna,45).
heuri(hyderabad,patna,46).
heuri(indore,patna,47).
heuri(jaipur,patna,48).
heuri(kanpur,patna,49).
heuri(lucknow,patna,50).
heuri(madras,patna,51).
heuri(nagpur,patna,52).
heuri(nasik,patna,53).
heuri(panjim,patna,54).
heuri(patna,patna,0).
heuri(pondicherry,patna,56).
heuri(pune,patna,57).
heuri(ahmedabad,pondicherry,39).
heuri(bangalore,pondicherry,40).
heuri(bhubaneshwar,pondicherry,41).
heuri(bombay,pondicherry,42).
heuri(calcutta,pondicherry,43).
heuri(chandigarh,pondicherry,44).
heuri(cochin,pondicherry,45).
heuri(delhi,pondicherry,46).
heuri(hyderabad,pondicherry,47).
heuri(indore,pondicherry,48).
heuri(jaipur,pondicherry,49).
heuri(kanpur,pondicherry,50).
heuri(lucknow,pondicherry,51).
heuri(madras,pondicherry,52).
heuri(nagpur,pondicherry,53).
heuri(nasik,pondicherry,54).
heuri(panjim,pondicherry,55).
heuri(patna,pondicherry,56).
heuri(pondicherry,pondicherry,0).
heuri(pune,pondicherry,58).
heuri(ahmedabad,pune,40).
heuri(bangalore,pune,41).
heuri(bhubaneshwar,pune,42).
heuri(bombay,pune,43).
heuri(calcutta,pune,44).
heuri(chandigarh,pune,45).
heuri(cochin,pune,46).
heuri(delhi,pune,47).
heuri(hyderabad,pune,48).
heuri(indore,pune,49).
heuri(jaipur,pune,50).
heuri(kanpur,pune,51).
heuri(lucknow,pune,52).
heuri(madras,pune,53).
heuri(nagpur,pune,54).
heuri(nasik,pune,55).
heuri(panjim,pune,56).
heuri(patna,pune,57).
heuri(pondicherry,pune,58).
heuri(pune,pune,0).
heuri(ahmedabad,ranchi,41).
heuri(bangalore,ranchi,42).
heuri(bhubaneshwar,ranchi,43).
heuri(bombay,ranchi,44).
heuri(calcutta,ranchi,45).
heuri(chandigarh,ranchi,46).
heuri(cochin,ranchi,47).
heuri(delhi,ranchi,48).
heuri(hyderabad,ranchi,49).
heuri(indore,ranchi,50).
heuri(jaipur,ranchi,51).
heuri(kanpur,ranchi,52).
heuri(lucknow,ranchi,53).
heuri(madras,ranchi,54).
heuri(nagpur,ranchi,55).
heuri(nasik,ranchi,56).
heuri(panjim,ranchi,57).
heuri(patna,ranchi,58).
heuri(pondicherry,ranchi,59).
heuri(pune,ranchi,60).
heuri(ahmedabad,shillong,42).
heuri(bangalore,shillong,43).
heuri(bhubaneshwar,shillong,44).
heuri(bombay,shillong,45).
heuri(calcutta,shillong,46).
heuri(chandigarh,shillong,47).
heuri(cochin,shillong,48).
heuri(delhi,shillong,49).
heuri(hyderabad,shillong,50).
heuri(indore,shillong,51).
heuri(jaipur,shillong,52).
heuri(kanpur,shillong,53).
heuri(lucknow,shillong,54).
heuri(madras,shillong,55).
heuri(nagpur,shillong,56).
heuri(nasik,shillong,57).
heuri(panjim,shillong,58).
heuri(patna,shillong,59).
heuri(pondicherry,shillong,60).
heuri(pune,shillong,61).
heuri(ahmedabad,shimla,43).
heuri(bangalore,shimla,44).
heuri(bhubaneshwar,shimla,45).
heuri(bombay,shimla,46).
heuri(calcutta,shimla,47).
heuri(chandigarh,shimla,48).
heuri(cochin,shimla,49).
heuri(delhi,shimla,50).
heuri(hyderabad,shimla,51).
heuri(indore,shimla,52).
heuri(jaipur,shimla,53).
heuri(kanpur,shimla,54).
heuri(lucknow,shimla,55).
heuri(madras,shimla,56).
heuri(nagpur,shimla,57).
heuri(nasik,shimla,58).
heuri(panjim,shimla,59).
heuri(patna,shimla,60).
heuri(pondicherry,shimla,61).
heuri(pune,shimla,62).
heuri(ahmedabad,surat,44).
heuri(bangalore,surat,45).
heuri(bhubaneshwar,surat,46).
heuri(bombay,surat,47).
heuri(calcutta,surat,48).
heuri(chandigarh,surat,49).
heuri(cochin,surat,50).
heuri(delhi,surat,51).
heuri(hyderabad,surat,52).
heuri(indore,surat,53).
heuri(jaipur,surat,54).
heuri(kanpur,surat,55).
heuri(lucknow,surat,56).
heuri(madras,surat,57).
heuri(nagpur,surat,58).
heuri(nasik,surat,59).
heuri(panjim,surat,60).
heuri(patna,surat,61).
heuri(pondicherry,surat,62).
heuri(pune,surat,63).
heuri(ahmedabad,trivandrum,45).
heuri(bangalore,trivandrum,46).
heuri(bhubaneshwar,trivandrum,47).
heuri(bombay,trivandrum,48).
heuri(calcutta,trivandrum,49).
heuri(chandigarh,trivandrum,50).
heuri(cochin,trivandrum,51).
heuri(delhi,trivandrum,52).
heuri(hyderabad,trivandrum,53).
heuri(indore,trivandrum,54).
heuri(jaipur,trivandrum,55).
heuri(kanpur,trivandrum,56).
heuri(lucknow,trivandrum,57).
heuri(madras,trivandrum,58).
heuri(nagpur,trivandrum,59).
heuri(nasik,trivandrum,60).
heuri(panjim,trivandrum,61).
heuri(patna,trivandrum,62).
heuri(pondicherry,trivandrum,63).
heuri(pune,trivandrum,64).
heuri(ahmedabad,varanasi,46).
heuri(bangalore,varanasi,47).
heuri(bhubaneshwar,varanasi,48).
heuri(bombay,varanasi,49).
heuri(calcutta,varanasi,50).
heuri(chandigarh,varanasi,51).
heuri(cochin,varanasi,52).
heuri(delhi,varanasi,53).
heuri(hyderabad,varanasi,54).
heuri(indore,varanasi,55).
heuri(jaipur,varanasi,56).
heuri(kanpur,varanasi,57).
heuri(lucknow,varanasi,58).
heuri(madras,varanasi,59).
heuri(nagpur,varanasi,60).
heuri(nasik,varanasi,61).
heuri(panjim,varanasi,62).
heuri(patna,varanasi,63).
heuri(pondicherry,varanasi,64).
heuri(pune,varanasi,65).
heuri(ahmedabad,vijayawada,47).
heuri(bangalore,vijayawada,48).
heuri(bhubaneshwar,vijayawada,49).
heuri(bombay,vijayawada,50).
heuri(calcutta,vijayawada,51).
heuri(chandigarh,vijayawada,52).
heuri(cochin,vijayawada,53).
heuri(delhi,vijayawada,54).
heuri(hyderabad,vijayawada,55).
heuri(indore,vijayawada,56).
heuri(jaipur,vijayawada,57).
heuri(kanpur,vijayawada,58).
heuri(lucknow,vijayawada,59).
heuri(madras,vijayawada,60).
heuri(nagpur,vijayawada,61).
heuri(nasik,vijayawada,62).
heuri(panjim,vijayawada,63).
heuri(patna,vijayawada,64).
heuri(pondicherry,vijayawada,65).
heuri(pune,vijayawada,66).
heuri(ahmedabad,vishakapatnam,48).
heuri(bangalore,vishakapatnam,49).
heuri(bhubaneshwar,vishakapatnam,50).
heuri(bombay,vishakapatnam,51).
heuri(calcutta,vishakapatnam,52).
heuri(chandigarh,vishakapatnam,53).
heuri(cochin,vishakapatnam,54).
heuri(delhi,vishakapatnam,55).
heuri(hyderabad,vishakapatnam,56).
heuri(indore,vishakapatnam,57).
heuri(jaipur,vishakapatnam,58).
heuri(kanpur,vishakapatnam,59).
heuri(lucknow,vishakapatnam,60).
heuri(madras,vishakapatnam,61).
heuri(nagpur,vishakapatnam,62).
heuri(nasik,vishakapatnam,63).
heuri(panjim,vishakapatnam,64).
heuri(patna,vishakapatnam,65).
heuri(pondicherry,vishakapatnam,66).
heuri(pune,vishakapatnam,67).